version: '3'
services:
  ceremonies:
    image: ruby:3.3
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:35729:35729"
    volumes:
      - .:/build
    command: bash /build/_bin/entrypoint.sh
